---
- name: Apply the Linux Standard Operating Environment baseline
  hosts: all
  become: true
  roles:
    - accounts_policy
    - audit_setup
    - boot_parameters
    - cron_setup
    - guest_agent
    - motd_issue
    - system_keyboard
    - system_locale
    - timesync
    - troubleshooting_tools
    - usbguard_setup
