---
soe_accounts_pass_max_days: 90
soe_accounts_pass_min_days: 1
soe_accounts_pass_warn_age: 7
soe_accounts_pwquality:
  minlen: 14
  dcredit: -1
  ucredit: -1
  lcredit: -1
  ocredit: -1
soe_accounts_sudoers_paths:
  - /etc/sudoers
  - /etc/sudoers.d
